"""Algorithm and rollout-mode adapters for execution contracts."""

from adapters.algorithms import AlgorithmAdapter, GRPOAdapter, PPOAdapter
from adapters.compliance.runtime import (
    AdapterConflictError,
    AdapterErrorKind,
    AdapterSupport,
    AdapterUnavailableError,
    ErrorContract,
    LaunchSpec,
    LifecycleAction,
    LifecycleCall,
    ManifestValidationError,
    RunnerKind,
    RuntimeAdapterError,
    SupportReport,
)
from adapters.contracts import (
    build_execution_contract,
    canonical_contract_id,
    validate_contract_observation,
    validate_execution_contract,
)
from adapters.control import (
    BridgeKind,
    BridgeTarget,
    CommandResult,
    ControlRequest,
    execute_control_argv,
    execute_control_request,
    resolve_bridge_target,
)
from adapters.execution import (
    BaseExecutionBackendAdapter,
    FakeExecutionBackendAdapter,
    RayExecutionBackendAdapter,
)
from adapters.frameworks import (
    BaseFrameworkAdapter,
    FakeFrameworkAdapter,
    OpenRLHFFrameworkAdapter,
    ReferenceCallbacks,
    VerlControlHook,
    VerlFrameworkAdapter,
    VerlObservation,
    VerlTrainerCallbacks,
    VerlWorkerBridge,
    WorkerCallbacks,
    WorkerIdentity,
    install_verl_control,
    install_verl_control_from_environment,
    observation_from_metrics,
    request_worker,
    worker_identity_from_environment,
)
from adapters.rollout_engines import (
    BaseRolloutEngineAdapter,
    FakeRolloutEngineAdapter,
    SGLangRolloutEngineAdapter,
    VLLMRolloutEngineAdapter,
)
from adapters.rollout_modes import (
    FullAsyncRolloutAdapter,
    PartialAsyncRolloutAdapter,
    RolloutModeAdapter,
    SyncRolloutAdapter,
)
from adapters.runtime_registry import RuntimeAdapterBundle, RuntimeAdapterRegistry
from adapters.trainers import BaseTrainerAdapter, FakeTrainerAdapter, PyTorchTrainerAdapter

__all__ = [
    "AdapterConflictError",
    "AdapterErrorKind",
    "AdapterSupport",
    "AdapterUnavailableError",
    "AlgorithmAdapter",
    "BaseExecutionBackendAdapter",
    "BaseFrameworkAdapter",
    "BaseRolloutEngineAdapter",
    "BaseTrainerAdapter",
    "BridgeKind",
    "BridgeTarget",
    "CommandResult",
    "ControlRequest",
    "ErrorContract",
    "FakeExecutionBackendAdapter",
    "FakeFrameworkAdapter",
    "FakeRolloutEngineAdapter",
    "FakeTrainerAdapter",
    "FullAsyncRolloutAdapter",
    "GRPOAdapter",
    "LaunchSpec",
    "LifecycleAction",
    "LifecycleCall",
    "ManifestValidationError",
    "OpenRLHFFrameworkAdapter",
    "PPOAdapter",
    "PartialAsyncRolloutAdapter",
    "PyTorchTrainerAdapter",
    "RayExecutionBackendAdapter",
    "ReferenceCallbacks",
    "RolloutModeAdapter",
    "RunnerKind",
    "RuntimeAdapterBundle",
    "RuntimeAdapterError",
    "RuntimeAdapterRegistry",
    "SGLangRolloutEngineAdapter",
    "SupportReport",
    "SyncRolloutAdapter",
    "VLLMRolloutEngineAdapter",
    "VerlControlHook",
    "VerlFrameworkAdapter",
    "VerlObservation",
    "VerlTrainerCallbacks",
    "VerlWorkerBridge",
    "WorkerCallbacks",
    "WorkerIdentity",
    "build_execution_contract",
    "canonical_contract_id",
    "execute_control_argv",
    "execute_control_request",
    "install_verl_control",
    "install_verl_control_from_environment",
    "observation_from_metrics",
    "request_worker",
    "resolve_bridge_target",
    "validate_contract_observation",
    "validate_execution_contract",
    "worker_identity_from_environment",
]
