import type {
  DecisionExplorerResult,
  DecisionRecord,
  ExperimentSummary,
  JobDetailResponse,
  JobSummary,
  MetricCard,
  OverviewResponse,
  ResourceSnapshot,
  RunSummary,
  SandboxRecord,
  TimelineEvent,
  TimelineResponse,
  TraceEventRecord,
  TopologySnapshot,
} from './types';

const now = '2026-08-27T14:32:00Z';

function metric(label: string, value: string, delta?: string, tone?: MetricCard['tone']): MetricCard {
  return { label, value, delta, tone };
}

export const jobs: JobSummary[] = [
  {
    id: 'job-live-017',
    name: 'PPO 策略突发训练',
    algorithm: 'PPO',
    state: 'running',
    rolloutMode: 'partially_async',
    dataKind: 'live',
    queue: 'priority-train',
    priority: 95,
    desiredUnits: 16,
    gpuRequired: true,
    createdAt: '2026-08-27T08:15:00Z',
    updatedAt: now,
    owner: 'ops-shift-a',
    policyVersion: 'policy-2026.08.27.5',
    traceId: 'trace-live-017',
    executionId: 'exec-live-017',
    currentRunId: 'run-live-017-a',
    latestRunState: 'JOB_RUN_STATE_RUNNING',
    runCount: 1,
    health: 'degraded',
  },
  {
    id: 'job-replay-204',
    name: '回放延迟审计',
    algorithm: 'GRPO',
    state: 'running',
    rolloutMode: 'sync',
    dataKind: 'replay',
    queue: 'audit',
    priority: 62,
    desiredUnits: 6,
    gpuRequired: false,
    createdAt: '2026-08-27T07:00:00Z',
    updatedAt: now,
    owner: 'analysis-bot',
    policyVersion: 'replay-2026.08.27.2',
    traceId: 'trace-replay-204',
    executionId: 'exec-replay-204',
    currentRunId: 'run-replay-204-a',
    latestRunState: 'JOB_RUN_STATE_RUNNING',
    runCount: 1,
    health: 'healthy',
  },
  {
    id: 'job-sim-031',
    name: '合成容量稳态压测',
    algorithm: 'A3C',
    state: 'paused',
    rolloutMode: 'fully_async',
    dataKind: 'synthetic',
    queue: 'simulation',
    priority: 40,
    desiredUnits: 10,
    gpuRequired: true,
    createdAt: '2026-08-26T23:45:00Z',
    updatedAt: now,
    owner: 'capacity-lab',
    policyVersion: 'sim-2026.08.26.9',
    traceId: 'trace-sim-031',
    executionId: 'exec-sim-031',
    currentRunId: 'run-sim-031-a',
    latestRunState: 'JOB_RUN_STATE_PAUSED',
    runCount: 1,
    health: 'stalled',
  },
];

export const runs: RunSummary[] = [
  {
    id: 'run-live-017-a',
    jobId: 'job-live-017',
    traceId: 'trace-live-017',
    state: 'JOB_RUN_STATE_RUNNING',
    attempt: 1,
    policyVersion: 'policy-2026.08.27.5',
    createdAt: '2026-08-27T08:16:00Z',
    startedAt: '2026-08-27T08:18:00Z',
    dataKind: 'live',
    componentHealth: [
      { component: 'scheduler', health: 'degraded', detail: '采样单元存在加速卡竞争' },
      { component: 'runtime', health: 'healthy', detail: '运行单元已收敛' },
    ],
  },
  {
    id: 'run-replay-204-a',
    jobId: 'job-replay-204',
    traceId: 'trace-replay-204',
    state: 'JOB_RUN_STATE_RUNNING',
    attempt: 2,
    policyVersion: 'replay-2026.08.27.2',
    createdAt: '2026-08-27T07:02:00Z',
    startedAt: '2026-08-27T07:03:00Z',
    dataKind: 'replay',
    componentHealth: [
      { component: 'scheduler', health: 'healthy', detail: '处理器放置稳定' },
      { component: 'runtime', health: 'healthy', detail: '回放流运行中' },
    ],
  },
  {
    id: 'run-sim-031-a',
    jobId: 'job-sim-031',
    traceId: 'trace-sim-031',
    state: 'JOB_RUN_STATE_PAUSED',
    attempt: 1,
    policyVersion: 'sim-2026.08.26.9',
    createdAt: '2026-08-26T23:47:00Z',
    startedAt: '2026-08-26T23:49:00Z',
    dataKind: 'synthetic',
    componentHealth: [
      { component: 'scheduler', health: 'failed', detail: '没有就绪的加速卡容量' },
      { component: 'runtime', health: 'progressing', detail: '已在安全点暂停' },
    ],
  },
];

export const decisions: DecisionRecord[] = [
  {
    id: 'dec-7104',
    sequence: 7104,
    jobId: 'job-live-017',
    runId: 'run-live-017-a',
    traceId: 'trace-live-017',
    stageId: 'actor-rollout',
    decidedAt: '2026-08-27T14:28:31Z',
    fallback: false,
    selectedPlanId: 'plan-7104',
    selectedCandidate: 'gpu-cell-4',
    policyVersion: 'policy-2026.08.27.5',
    summary: '将两个采样单元绑定到 gpu-cell-4，并保留资源份额余量。',
    actions: [
      {
        actionId: 'act-7104-a',
        type: 'bind',
        sandboxId: 'sbx-live-a14',
        targetId: 'gpu-cell-4',
        status: 'succeeded',
        detail: '第 7 代绑定已应用，使用一个 A100 切片。',
      },
      {
        actionId: 'act-7104-b',
        type: 'resize',
        sandboxId: 'sbx-live-a09',
        targetId: 'gpu-cell-4',
        status: 'succeeded',
        detail: '处理器预留已提高到 2400 毫核。',
      },
    ],
  },
  {
    id: 'dec-7098',
    sequence: 7098,
    jobId: 'job-sim-031',
    traceId: 'trace-sim-031',
    stageId: 'learner',
    decidedAt: '2026-08-27T13:51:11Z',
    fallback: true,
    fallbackReason: 'NO_READY_GPU_CAPACITY',
    policyVersion: 'sim-2026.08.26.9',
    summary: '没有兼容且保持就绪的加速卡，调度器返回回退结果。',
    actions: [],
  },
  {
    id: 'dec-7084',
    sequence: 7084,
    jobId: 'job-replay-204',
    traceId: 'trace-replay-204',
    stageId: 'replay',
    decidedAt: '2026-08-27T13:05:20Z',
    fallback: false,
    selectedPlanId: 'plan-7084',
    selectedCandidate: 'cpu-bank-2',
    policyVersion: 'replay-2026.08.27.2',
    summary: '回放工作单元已在 cpu-bank-2 收敛，无需额外变更。',
    actions: [
      {
        actionId: 'act-7084-a',
        type: 'resume',
        sandboxId: 'sbx-replay-4',
        targetId: 'cpu-bank-2',
        status: 'succeeded',
        detail: '已从序列 18232 的安全点恢复。',
      },
    ],
  },
];

export const sandboxes: SandboxRecord[] = [
  {
    id: 'sbx-live-a14',
    jobId: 'job-live-017',
    runId: 'run-live-017-a',
    state: 'running',
    generation: 7,
    nodeLabel: 'gpu-cell-4',
    gpuAttached: true,
    share: 0.5,
    priority: 95,
    safePoint: true,
    offloaded: false,
    updatedAt: '2026-08-27T14:29:03Z',
    bindingSummary: 'A100:0, cpu=2400m, memory=8Gi',
  },
  {
    id: 'sbx-live-a09',
    jobId: 'job-live-017',
    runId: 'run-live-017-a',
    state: 'paused',
    generation: 3,
    nodeLabel: 'gpu-cell-4',
    gpuAttached: true,
    share: 0.25,
    priority: 82,
    safePoint: true,
    offloaded: false,
    updatedAt: '2026-08-27T14:24:10Z',
    bindingSummary: 'A100:1, cpu=2400m, memory=6Gi',
  },
  {
    id: 'sbx-replay-4',
    jobId: 'job-replay-204',
    state: 'running',
    generation: 2,
    nodeLabel: 'cpu-bank-2',
    gpuAttached: false,
    share: 0.7,
    priority: 62,
    safePoint: false,
    offloaded: false,
    updatedAt: '2026-08-27T13:06:01Z',
    bindingSummary: 'cpu=1800m, memory=3Gi',
  },
  {
    id: 'sbx-sim-2',
    jobId: 'job-sim-031',
    state: 'sleeping',
    generation: 5,
    nodeLabel: 'queue-simulation',
    gpuAttached: false,
    share: 0.1,
    priority: 40,
    safePoint: true,
    offloaded: true,
    updatedAt: '2026-08-27T13:52:07Z',
    bindingSummary: '等待加速卡容量时已卸载',
  },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: 'evt-901',
    jobId: 'job-live-017',
    runId: 'run-live-017-a',
    title: '策略已发布',
    type: 'policy-published',
    occurredAt: '2026-08-27T14:20:00Z',
    sequence: 901,
    phase: 'learner',
    dataKind: 'live',
    severity: 'info',
    summary: '策略 policy-2026.08.27.5 已发布到采样单元。',
  },
  {
    id: 'evt-904',
    jobId: 'job-live-017',
    runId: 'run-live-017-a',
    title: '背压发生变化',
    type: 'backpressure',
    occurredAt: '2026-08-27T14:26:11Z',
    sequence: 904,
    phase: 'actor-rollout',
    dataKind: 'live',
    severity: 'warn',
    summary: '回放缓冲区水位超过 78%。',
  },
  {
    id: 'evt-909',
    jobId: 'job-live-017',
    runId: 'run-live-017-a',
    title: '决策已应用',
    type: 'decision-applied',
    occurredAt: '2026-08-27T14:28:31Z',
    sequence: 909,
    phase: 'actor-rollout',
    sandboxId: 'sbx-live-a14',
    decisionId: 'dec-7104',
    dataKind: 'live',
    severity: 'info',
    summary: '已应用决策 dec-7104，重新平衡采样容量。',
  },
  {
    id: 'evt-915',
    jobId: 'job-sim-031',
    runId: 'run-sim-031-a',
    title: '已到达安全点',
    type: 'safe-point',
    occurredAt: '2026-08-27T13:50:30Z',
    sequence: 915,
    phase: 'learner',
    sandboxId: 'sbx-sim-2',
    dataKind: 'synthetic',
    severity: 'warn',
    summary: '合成训练单元在等待加速卡时进入安全点。',
  },
  {
    id: 'evt-920',
    jobId: 'job-replay-204',
    runId: 'run-replay-204-a',
    title: '样本已消费',
    type: 'sample-consumed',
    occurredAt: '2026-08-27T13:07:01Z',
    sequence: 920,
    phase: 'replay',
    sandboxId: 'sbx-replay-4',
    dataKind: 'replay',
    severity: 'info',
    summary: '已消费 1200 个回放样本，未检测到漂移。',
  },
];

// Trace 使用独立的 span 数据，不从控制事件时间线推测。每个持续时间、父子关系和
// request/worker 身份都代表采集端实际应上报的字段，便于在没有 GPU 的本机环境验证
// Perfetto 风格的多轨交互；真实 HTTP 模式始终读取 Runtime 持久化的 TraceEvent。
export const traceEvents: TraceEventRecord[] = [
  {
    id: 'trace-trainer-step-42', jobId: 'job-live-017', runId: 'run-live-017-a',
    traceId: 'trace-live-017', executionId: 'exec-live-017', sequence: 1001,
    occurredAt: '2026-08-27T14:28:30.000Z', type: 'phase_started', phaseId: 'actor-rollout',
    stageId: 'actor-rollout', algorithm: 'PPO', rolloutMode: 'partially_async',
    policyVersion: 'policy-2026.08.27.5', bufferLevel: 42, safePoint: false, generation: 7,
    dataKind: 'live', attributes: {
      component: 'trainer', track: '训练步骤 #42', display_name: '采样与训练迭代',
      span_id: 'span-train-42', duration_ms: '3200', batch_size: '32',
    },
  },
  {
    id: 'trace-request-1842', jobId: 'job-live-017', runId: 'run-live-017-a',
    traceId: 'trace-live-017', executionId: 'exec-live-017', sequence: 1002,
    occurredAt: '2026-08-27T14:28:30.120Z', type: 'sample_produced', phaseId: 'actor-rollout',
    stageId: 'agent-loop', algorithm: 'PPO', rolloutMode: 'partially_async',
    policyVersion: 'policy-2026.08.27.5', bufferLevel: 43, safePoint: false, generation: 7,
    dataKind: 'live', attributes: {
      component: 'request', track: '请求 req-1842', display_name: '智能体请求', request_id: 'req-1842',
      span_id: 'span-request-1842', parent_span_id: 'span-train-42', duration_ms: '1380',
    },
  },
  {
    id: 'trace-agent-1842', jobId: 'job-live-017', runId: 'run-live-017-a',
    traceId: 'trace-live-017', executionId: 'exec-live-017', sequence: 1003,
    occurredAt: '2026-08-27T14:28:30.170Z', type: 'phase_started', phaseId: 'actor-rollout',
    stageId: 'agent-loop', algorithm: 'PPO', rolloutMode: 'partially_async',
    policyVersion: 'policy-2026.08.27.5', bufferLevel: 43, safePoint: false, generation: 7,
    dataKind: 'live', attributes: {
      component: 'request', track: '智能体循环 / req-1842', display_name: '提示词与工具编排', request_id: 'req-1842',
      span_id: 'span-agent-1842', parent_span_id: 'span-request-1842', duration_ms: '260',
    },
  },
  {
    id: 'trace-executor-1842', jobId: 'job-live-017', runId: 'run-live-017-a',
    traceId: 'trace-live-017', executionId: 'exec-live-017', sequence: 1004,
    occurredAt: '2026-08-27T14:28:30.460Z', type: 'decision_applied', phaseId: 'decode',
    stageId: 'executor', algorithm: 'PPO', rolloutMode: 'partially_async',
    policyVersion: 'policy-2026.08.27.5', bufferLevel: 44, safePoint: false,
    decisionId: 'dec-7104', generation: 7, dataKind: 'live', attributes: {
      component: 'executor', track: '推理执行器 #0', display_name: '连续批处理调度', request_id: 'req-1842',
      executor_id: 'executor-0', span_id: 'span-executor-1842', parent_span_id: 'span-request-1842',
      duration_ms: '690', batch_size: '16',
    },
  },
  {
    id: 'trace-worker-0-1842', jobId: 'job-live-017', runId: 'run-live-017-a',
    traceId: 'trace-live-017', executionId: 'exec-live-017', sequence: 1005,
    occurredAt: '2026-08-27T14:28:30.510Z', type: 'sample_consumed', phaseId: 'decode',
    stageId: 'model-forward', algorithm: 'PPO', rolloutMode: 'partially_async',
    policyVersion: 'policy-2026.08.27.5', bufferLevel: 44, safePoint: false,
    sandboxId: 'sbx-live-a14', generation: 7, dataKind: 'live', attributes: {
      component: 'worker', track: '工作进程 #0', display_name: '模型前向计算', request_id: 'req-1842',
      executor_id: 'executor-0', worker_id: 'worker-0', span_id: 'span-worker-0-1842',
      parent_span_id: 'span-executor-1842', duration_ms: '310', batch_size: '8', device_id: 'GPU-0',
    },
  },
  {
    id: 'trace-worker-1-1842', jobId: 'job-live-017', runId: 'run-live-017-a',
    traceId: 'trace-live-017', executionId: 'exec-live-017', sequence: 1006,
    occurredAt: '2026-08-27T14:28:30.510Z', type: 'sample_consumed', phaseId: 'decode',
    stageId: 'model-forward', algorithm: 'PPO', rolloutMode: 'partially_async',
    policyVersion: 'policy-2026.08.27.5', bufferLevel: 44, safePoint: false,
    sandboxId: 'sbx-live-a14', generation: 7, dataKind: 'live', attributes: {
      component: 'worker', track: '工作进程 #1', display_name: '模型前向计算', request_id: 'req-1842',
      executor_id: 'executor-0', worker_id: 'worker-1', span_id: 'span-worker-1-1842',
      parent_span_id: 'span-executor-1842', duration_ms: '470', batch_size: '8', device_id: 'GPU-1',
    },
  },
  {
    id: 'trace-request-1843', jobId: 'job-live-017', runId: 'run-live-017-a',
    traceId: 'trace-live-017', executionId: 'exec-live-017', sequence: 1007,
    occurredAt: '2026-08-27T14:28:30.480Z', type: 'sample_produced', phaseId: 'actor-rollout',
    stageId: 'agent-loop', algorithm: 'PPO', rolloutMode: 'partially_async',
    policyVersion: 'policy-2026.08.27.5', bufferLevel: 46, safePoint: false, generation: 7,
    dataKind: 'live', attributes: {
      component: 'request', track: '请求 req-1843', display_name: '智能体请求（长尾）', request_id: 'req-1843',
      span_id: 'span-request-1843', parent_span_id: 'span-train-42', duration_ms: '2320',
    },
  },
  {
    id: 'trace-tool-1843', jobId: 'job-live-017', runId: 'run-live-017-a',
    traceId: 'trace-live-017', executionId: 'exec-live-017', sequence: 1008,
    occurredAt: '2026-08-27T14:28:30.520Z', type: 'backpressure_changed', phaseId: 'actor-rollout',
    stageId: 'agent-loop', algorithm: 'PPO', rolloutMode: 'partially_async',
    policyVersion: 'policy-2026.08.27.5', bufferLevel: 78, safePoint: false, generation: 7,
    dataKind: 'live', attributes: {
      component: 'request', track: '工具调用 / req-1843', display_name: '工具调用等待', request_id: 'req-1843',
      span_id: 'span-tool-1843', parent_span_id: 'span-request-1843', duration_ms: '280',
    },
  },
  {
    id: 'trace-executor-1843', jobId: 'job-live-017', runId: 'run-live-017-a',
    traceId: 'trace-live-017', executionId: 'exec-live-017', sequence: 1009,
    occurredAt: '2026-08-27T14:28:30.860Z', type: 'decision_applied', phaseId: 'decode',
    stageId: 'executor', algorithm: 'PPO', rolloutMode: 'partially_async',
    policyVersion: 'policy-2026.08.27.5', bufferLevel: 70, safePoint: false,
    decisionId: 'dec-7104', generation: 7, dataKind: 'live', attributes: {
      component: 'executor', track: '推理执行器 #0', display_name: '长尾批次调度', request_id: 'req-1843',
      executor_id: 'executor-0', span_id: 'span-executor-1843', parent_span_id: 'span-request-1843',
      duration_ms: '1420', batch_size: '16',
    },
  },
  {
    id: 'trace-worker-0-1843', jobId: 'job-live-017', runId: 'run-live-017-a',
    traceId: 'trace-live-017', executionId: 'exec-live-017', sequence: 1010,
    occurredAt: '2026-08-27T14:28:30.930Z', type: 'sample_consumed', phaseId: 'decode',
    stageId: 'model-forward', algorithm: 'PPO', rolloutMode: 'partially_async',
    policyVersion: 'policy-2026.08.27.5', bufferLevel: 70, safePoint: false,
    sandboxId: 'sbx-live-a14', generation: 7, dataKind: 'live', attributes: {
      component: 'worker', track: '工作进程 #0', display_name: '模型前向计算', request_id: 'req-1843',
      executor_id: 'executor-0', worker_id: 'worker-0', span_id: 'span-worker-0-1843',
      parent_span_id: 'span-executor-1843', duration_ms: '840', batch_size: '8', device_id: 'GPU-0',
    },
  },
  {
    id: 'trace-worker-1-1843', jobId: 'job-live-017', runId: 'run-live-017-a',
    traceId: 'trace-live-017', executionId: 'exec-live-017', sequence: 1011,
    occurredAt: '2026-08-27T14:28:30.930Z', type: 'sample_consumed', phaseId: 'decode',
    stageId: 'model-forward', algorithm: 'PPO', rolloutMode: 'partially_async',
    policyVersion: 'policy-2026.08.27.5', bufferLevel: 70, safePoint: false,
    sandboxId: 'sbx-live-a14', generation: 7, dataKind: 'live', attributes: {
      component: 'worker', track: '工作进程 #1', display_name: '模型前向计算（长尾）', request_id: 'req-1843',
      executor_id: 'executor-0', worker_id: 'worker-1', span_id: 'span-worker-1-1843',
      parent_span_id: 'span-executor-1843', duration_ms: '1120', batch_size: '8', device_id: 'GPU-1',
    },
  },
  {
    id: 'trace-safe-point-42', jobId: 'job-live-017', runId: 'run-live-017-a',
    traceId: 'trace-live-017', executionId: 'exec-live-017', sequence: 1012,
    occurredAt: '2026-08-27T14:28:33.200Z', type: 'safe_point_reached', phaseId: 'learner',
    stageId: 'trainer', algorithm: 'PPO', rolloutMode: 'partially_async',
    policyVersion: 'policy-2026.08.27.5', bufferLevel: 35, safePoint: true, generation: 7,
    dataKind: 'live', attributes: {
      component: 'trainer', track: '训练步骤 #42', display_name: '到达安全点',
      span_id: 'span-safe-point-42', parent_span_id: 'span-train-42',
    },
  },
];

export const topology: TopologySnapshot = {
  runId: 'run-live-017-a',
  manifestId: 'manifest-live-017-a',
  nodes: [
    { id: 'queue-priority', label: 'priority-train', kind: 'queue', status: 'busy', gpu: false, utilization: 0.92 },
    { id: 'queue-audit', label: 'audit', kind: 'queue', status: 'ready', gpu: false, utilization: 0.48 },
    { id: 'job-live-017', label: 'PPO 策略突发训练', kind: 'job', status: 'degraded', gpu: true, utilization: 0.88 },
    { id: 'job-replay-204', label: '回放延迟审计', kind: 'job', status: 'ready', gpu: false, utilization: 0.51 },
    { id: 'gpu-cell-4', label: 'gpu-cell-4', kind: 'device', status: 'busy', gpu: true, share: 0.94, utilization: 0.97 },
    { id: 'cpu-bank-2', label: 'cpu-bank-2', kind: 'device', status: 'ready', gpu: false, share: 0.61, utilization: 0.59 },
    { id: 'sbx-live-a14', label: 'sbx-live-a14', kind: 'sandbox', status: 'busy', gpu: true, share: 0.5, utilization: 0.72 },
    { id: 'sbx-replay-4', label: 'sbx-replay-4', kind: 'sandbox', status: 'ready', gpu: false, share: 0.7, utilization: 0.46 },
  ],
  edges: [
    { from: 'queue-priority', to: 'job-live-017', relation: 'feeds' },
    { from: 'queue-audit', to: 'job-replay-204', relation: 'feeds' },
    { from: 'job-live-017', to: 'sbx-live-a14', relation: 'runs-in' },
    { from: 'job-replay-204', to: 'sbx-replay-4', relation: 'runs-in' },
    { from: 'sbx-live-a14', to: 'gpu-cell-4', relation: 'scheduled-on' },
    { from: 'sbx-replay-4', to: 'cpu-bank-2', relation: 'scheduled-on' },
  ],
  lastUpdated: now,
};

export const resources: ResourceSnapshot = {
  id: 'snapshot-heterogeneous-demo',
  revision: 42,
  observedAt: now,
  pendingUnits: 2,
  devices: [
    {
      id: 'GPU-A10-DEMO',
      name: 'NVIDIA A10',
      kind: 'gpu',
      node: 'gpu-a10-01',
      provider: 'nvidia',
      health: 'ready',
      memoryBytes: 24 * 1024 ** 3,
      allocatableMemoryBytes: 8 * 1024 ** 3,
      capacity: 1,
      allocatable: 0.3,
      utilization: 0.7,
      activeMode: 'hami',
      availableModes: ['full', 'hami', 'mps'],
      capabilities: ['hami-vgpu', 'nvidia-gpu', 'nvidia-mps'],
      driverVersion: '580.178.04',
    },
    {
      id: 'GPU-H100-DEMO',
      name: 'NVIDIA H100 80GB',
      kind: 'gpu',
      node: 'gpu-h100-02',
      provider: 'nvidia',
      health: 'ready',
      memoryBytes: 80 * 1024 ** 3,
      allocatableMemoryBytes: 80 * 1024 ** 3,
      capacity: 1,
      allocatable: 1,
      utilization: 0,
      activeMode: 'full',
      availableModes: ['full', 'hami', 'mps', 'mig'],
      capabilities: ['hami-vgpu', 'nvidia-gpu', 'nvidia-mig', 'nvidia-mps'],
      driverVersion: '580.178.04',
    },
    {
      id: 'MIG-A100-DEMO',
      name: 'NVIDIA A100 · 1g.10gb',
      kind: 'gpu',
      node: 'gpu-a100-03',
      provider: 'nvidia',
      health: 'ready',
      memoryBytes: 10 * 1024 ** 3,
      allocatableMemoryBytes: 10 * 1024 ** 3,
      capacity: 1,
      allocatable: 1,
      utilization: 0,
      activeMode: 'mig',
      availableModes: ['mig'],
      capabilities: ['nvidia-gpu', 'nvidia-mig'],
      driverVersion: '580.178.04',
      parentUuid: 'GPU-A100-MIG-PARENT-DEMO',
      profile: '1g.10gb',
    },
    {
      id: 'GPU-L40S-DEMO',
      name: 'NVIDIA L40S',
      kind: 'gpu',
      node: 'gpu-l40s-04',
      provider: 'nvidia',
      health: 'degraded',
      memoryBytes: 48 * 1024 ** 3,
      allocatableMemoryBytes: 48 * 1024 ** 3,
      capacity: 1,
      allocatable: 1,
      utilization: 0,
      activeMode: 'full',
      availableModes: ['full', 'hami', 'mps'],
      capabilities: ['hami-vgpu', 'nvidia-gpu', 'nvidia-mps'],
      driverVersion: '580.178.04',
    },
  ],
  allocations: [
    {
      id: 'allocation-a10-rollout',
      jobId: 'job-live-017',
      runId: 'run-live-017-a',
      sandboxId: 'sbx-live-a14',
      stageId: 'actor-rollout',
      deviceIds: ['GPU-A10-DEMO'],
      share: 0.7,
      memoryBytes: 16 * 1024 ** 3,
      state: 'ALLOCATION_STATE_ACTIVE',
      generation: 7,
    },
  ],
};

export const experiments: ExperimentSummary[] = [
  {
    id: 'exp-ppo-compare',
    name: 'PPO 采样策略对比',
    state: 'running',
    createdAt: '2026-08-27T05:00:00Z',
    summary: '在相同队列压力下对比真实 PPO 与回放基线。',
    runs: [
      {
        id: 'run-live-ppo',
        experimentId: 'exp-ppo-compare',
        runId: 'run-live-ppo',
        label: '真实运行',
        kind: 'live',
        dataKind: 'live',
        policyVersion: 'policy-2026.08.27.5',
        configHash: 'cfg-a9f4',
        codeRevision: 'rev-a13bc1',
        summary: '吞吐最高，但回放缓冲区压力有所上升。',
        metrics: [
          metric('奖励值', '0.81', '+0.04', 'good'),
          metric('每秒样本', '18.4k', '+2.3k', 'good'),
          metric('决策延迟 P95', '211ms', '+44ms', 'warn'),
        ],
      },
      {
        id: 'run-replay-ppo',
        experimentId: 'exp-ppo-compare',
        runId: 'run-replay-ppo',
        label: '回放基线',
        kind: 'replay',
        dataKind: 'replay',
        policyVersion: 'replay-2026.08.27.2',
        configHash: 'cfg-a9f4',
        codeRevision: 'rev-a13bc1',
        summary: '吞吐较低，但决策延迟范围更稳定。',
        metrics: [
          metric('奖励值', '0.76', '-0.01', 'neutral'),
          metric('每秒样本', '11.1k', '-1.2k', 'warn'),
          metric('决策延迟 P95', '128ms', '-12ms', 'good'),
        ],
      },
    ],
  },
  {
    id: 'exp-capacity-sim',
    name: '合成加速卡紧缺演练',
    state: 'failed',
    createdAt: '2026-08-26T21:10:00Z',
    completedAt: '2026-08-27T13:53:00Z',
    summary: '合成演练在训练单元收敛前耗尽了就绪加速卡容量。',
    runs: [
      {
        id: 'run-sim-a3c',
        experimentId: 'exp-capacity-sim',
        runId: 'run-sim-a3c',
        label: '合成演练',
        kind: 'simulation',
        dataKind: 'synthetic',
        policyVersion: 'sim-2026.08.26.9',
        configHash: 'cfg-b29d',
        codeRevision: 'rev-ff02a1',
        summary: '因加速卡不可用，沿回退路径停止。',
        metrics: [
          metric('加速卡就绪率', '0.02', '-0.11', 'critical'),
          metric('回退次数', '17', '+12', 'critical'),
          metric('检查点漂移', '0.0', '稳定', 'good'),
        ],
      },
    ],
  },
];

export const overview: OverviewResponse = {
  metrics: [
    metric('活动任务', '3', '+1', 'good'),
    metric('决策流延迟', '214ms', '+37ms', 'warn'),
    metric('加速卡余量', '6%', '-4%', 'critical'),
    metric('回放漂移', '0.3%', '-0.1%', 'good'),
  ],
  jobs,
  experiments,
  decisions,
  capabilities: {
    protocolVersion: 'v0.3',
    dataKinds: ['DATA_KIND_SYNTHETIC', 'DATA_KIND_REPLAY', 'DATA_KIND_LIVE'],
    pagination: 'opaque_stable_token',
  },
  systemHealth: {
    status: 'ok',
    observedAt: now,
    counts: {
      jobs: jobs.length,
      runs: runs.length,
      operations: 5,
      decisions: decisions.length,
      replays: 1,
      experiments: experiments.length,
    },
  },
  alerts: [
    {
      id: 'al-1',
      title: '加速卡容量降级',
      tone: 'critical',
      detail: '就绪加速卡容量低于策略下限，合成训练流量已被隔离。',
    },
    {
      id: 'al-2',
      title: '回放链路稳定',
      tone: 'info',
      detail: '回放工作负载保持在目标延迟范围内，可用于安全对比。',
    },
  ],
};

export function getJobDetail(jobId: string): JobDetailResponse | undefined {
  const job = jobs.find((entry) => entry.id === jobId);
  if (!job) {
    return undefined;
  }
  return {
    job,
    runs: runs.filter((entry) => entry.jobId === jobId),
    selectedRunId: runs.find((entry) => entry.jobId === jobId)?.id,
    decisions: decisions.filter((entry) => entry.jobId === jobId),
    sandboxes: sandboxes.filter((entry) => entry.jobId === jobId),
    metrics: [
      metric('期望单元', String(job.desiredUnits)),
      metric('优先级', `${job.priority}`),
      metric('健康状态', job.health === 'healthy' ? '健康' : job.health === 'degraded' ? '降级' : '停滞', undefined, job.health === 'healthy' ? 'good' : job.health === 'degraded' ? 'warn' : 'critical'),
    ],
  };
}

export const timeline: TimelineResponse = { events: timelineEvents };

export function getRunList(jobId: string): RunSummary[] {
  return runs.filter((entry) => entry.jobId === jobId);
}

export function getDecisionExplorer(decisionId: string): DecisionExplorerResult | undefined {
  const decision = decisions.find((entry) => entry.id === decisionId);
  if (!decision) {
    return undefined;
  }
  return {
    selectedDecision: decision,
    candidates: [
      { id: 'gpu-cell-4', deviceLabel: 'gpu-cell-4', score: 0.91, reason: '在所有就绪加速卡节点中余量最高。', selected: true },
      { id: 'gpu-cell-2', deviceLabel: 'gpu-cell-2', score: 0.72, reason: '满足约束，但未被策略选中。', selected: false },
    ],
    rejectedCandidates: [
      { id: 'cpu-bank-2', reason: 'CAPABILITY_MISMATCH', detail: '该工作负载需要加速卡能力。' },
    ],
    relatedActions: decision.actions,
  };
}
