apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.serviceAccount.name }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
